spring.application.name=JwtDemoApplication
spring.datasource.url=jdbc:postgresql://localhost:5432/jwt_demo
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.security=TRACE

// fix git commit issue - verify!